### ISSUE TITLE
ROTINA criada através de sites como referência

### ISSUE THREAD

**Issue by luanvsky** [luanvsky/confreg-dw-v.0#88]
### Discussed in https://github.com/luanvsky/confreg-dw-v.0/discussions/84

<div type='discussions-op-text'>

<sup>Originally posted by **luanvsky** November 22, 2023</sup>
# ROTINA
<details><summary>Etapas</summary>
<p>

- [x] Os trabalhos do conformista de gestão se iniciam com o recebimento do processo no sistema SEI!, ou equivalente.
- [x] Após o recebimento, será feita a análise do processo, o qual deve ser observado a constatação de documentos que ofereçam sustentação aos registros lançados no SIAFI.
- [x] Confirmada a regularidade dos lançamentos, será efetuada a conformidade diária no comando ATUCONFREG.
- [x]  A análise do processo é feita na ordem de recebimento dos processos.
- [x]  Segue roteiro para análise documental nos anexos I ao X.
- [x]  Após todos os trâmites necessários, e realizada a conformidade final, o processo será arquivado no sistema SEI!, ou equivalente.
- [x]  Em caso de férias, folga ou ausência do Conformista, será comunicado ao substituto por correio eletrônico, com antecedência, para que o mesmo proceda com a conformidade de registro de gestão.
- [x]  Em caso de eventualidades, será informado verbalmente ou contatado por telefone.

</p>
</details> 

<details><summary>NOTA DE EMPENHO – NE</summary>
<p>

- [ ]  Se o credor está cadastrado e habilitado no SICAF;
- [ ]  Se a data de emissão do documento SICAF é igual a data de emissão do empenho.
- [ ]  Verificar se a espécie de empenho está condizente com o fato registrado.
- [ ]  Verificar se o favorecido da NE é o vencedor do processo licitatório para os itens 
 empenhados ou o escolhido por dispensa/inexigibilidade de licitação.
- [ ]  Se a observação é sucinta e objetiva e de acordo com o objeto contratado;
- [ ]  Se a classificação orçamentária está correta (impressão do relatório “ORÇAMENTO” no Tesouro Gerencial):
- [ ]  Esfera;
- [ ]  Órgão;
- [ ]  Programa de trabalho resumido;
- [ ]  Fonte;
- [ ]  Natureza da despesa; e
- [ ]  Plano Interno.
- [ ]  Tipo de empenho: 
- [ ]  Estimativo: corresponde à despesa cujo montante não se possa determinar;
- [ ]  Ordinário: correspondente à despesa de valor determinado e se o seu pagamento ocorrerá de uma só vez; ou
- [ ] Global: corresponde à despesa contratual e outras de valor determinado, sujeitas a parcelamento.
- [ ]  Base legal da contratação:
- [ ] Modalidade de Licitação;
- [ ] Amparo;
- [ ] Inciso;
- [ ] Processo; e
- [ ] Referência.
- [ ] Especificação do material ou serviço de acordo com o processo de contratação:
- [ ] Subitem;
- [ ] Quantidade;
- [ ] Valor unitário; e
- [ ] Descrição do item.

</p>
</details> 

<details><summary>NOTA DE LANÇAMENTO NO SISTEMA – NS</summary>
<p>

- [ ] Verificação do SICAF;
- [ ] Se a data de emissão do SICAF é igual a data de lançamento da NS;
- [ ] Caso o credor esteja com o SICAF vencido, se faz necessário constar o despacho para o ordenador de despesa, solicitando a autorização de pagamento;
- [ ] Verificar se o fornecedor é Optante pelo Simples;
- [ ] Verificar se consta o documento de regularidade da nota fiscal (alguns tipos de notas não permitem a verificação);
- [ ] Data da emissão igual a data do ateste do fiscal técnico ou do recebimento provisório;
- [ ] Favorecido corresponde ao do documento hábil;
- [ ] Observar se a sigla do título de crédito está em conformidade com a operação registrada;

Exemplos mais comumente utilizados:
TIPO| DESCRIÇÃO
:---|:---
RC|Registra os atos e fatos contábeis em contas de controles diversos, das
classes 7 e 8.
NP| Documento hábil para realização de compromissos vinculados a nota
fiscal/fatura de pagamento.
PA |Registra os fenômenos exclusivamente patrimoniais, tais como depreciação,
consumo de estoque, entre outros.
SF|Pagamento de Suprimento de Fundos.
AV |Autorização de Viagens (Diárias); Pagamento de passagens e diárias.

- [ ] Se, no campo “Observação” da NS, foi informado o número e data do documento hábil, o nome favorecido (credor), número do contrato e informação das retenções tributárias e outras;
- [ ] Se o valor liquidado do favorecido corresponde ao do documento hábil;
- [ ] Verificação dos valores retidos e dos códigos dos tributos.
- [ ] Se a classificação orçamentária e o número do empenho correspondem ao empenho do processo/contrato (verificar despacho do Setor de Orçamento e Finanças); 
- [ ] Verificar se a conta do patrimônio/almoxarifado/despesa está de acordo com o objeto da compra; e
- [ ] Caso exista contrato, verificar o registro do contrato na NS.

</p>
</details> 

<details><summary>ORDEM BANCÁRIA – OB</summary>
<p>

- [x] Verificação do SICAF;
- [x] Caso o credor esteja com o SICAF vencido, se faz necessário constar o despacho do ordenador de despesa, autorizando o pagamento; 
- [x] Se a data de emissão é igual ou posterior ao compromisso assumido, quando se tratar de despesa legalmente empenhada;
- [x] Favorecido corresponde ao do documento hábil (no caso de boletos bancários o CNPJ do favorecido será diferente do documento hábil);
- [x] Se o domicílio bancário do favorecido corresponde aos dados cadastrais (no caso de boletos bancários ou FATURAS a conta corrente será “FATURA”, e deverá constar o documento “LISTA DE FATURA”);
- [x] Se, no campo “Observação” da OB, foi informado o número e data do documento hábil, o nome favorecido (credor), número do contrato e informação das retenções;
- [x] Se o valor pago ao favorecido corresponde ao do documento hábil, deduzido dos tributos (IR, CSSLL, PIS, COFINS, INSS, ISS); e
- [x] Se os recursos financeiros utilizados estão de acordo com a categoria de gasto e a fonte 
sub-repassada pela Diretoria de Contabilidade ou pelo Concedente, no caso de Convênio. 

</p>
</details> 

<details><summary>DOCUMENTO DE ARRECADAÇÃO DE RECEITAS FEDERAIS – DARF</summary>
<p>

- [ ] Verificar se o credor “não é optante pelos SIMPLES” (OBS: se for optante não haverá DARF);
- [ ]  Verificar se a data do período de apuração é igual a data de emissão;
- [ ] Se o campo “Contribuinte” foi preenchido com o CPF/CNPJ do fornecedor, exceto em serviço de reembolso de combustível, nesse caso o CNPJ não será o da administradora e sim da empresa fornecedora do combustível;
- [ ] Verificar, levando-se em consideração o valor registrado no campo “Base de Cálculo” e o percentual das alíquotas, se o valor recolhido está correto; e
- [ ] Verificar se o código de receita está correto.
- [ ] Se no campo “Observação” foram identificados os tributos, valores, as alíquotas percentuais de cada retenção, e o número do documento hábil;

</p>
</details> 

<details><summary>GUIA DE RECOLHIMENTO DA UNIÃO – GRU</summary>
<p>

- [ ] Verificação do SICAF;
- [ ] Se a data de emissão é igual ou posterior ao compromisso assumido, quando se tratar de despesa legalmente empenhada;
- [ ] Favorecido corresponde ao do documento hábil;
- [ ] Se o código de recolhimento do favorecido corresponde do documento hábil;
- [ ] Se o valor pago ao favorecido corresponde ao valor do documento hábil, deduzido dos tributos (IR, CSSLL, PIS, COFINS, INSS, ISS); e
- [ ] Se os recursos financeiros utilizados estão de acordo com a categoria de gasto e a fonte sub-repassada pela Diretoria de Contabilidade ou pelo Concedente, no caso de Convênio. (Recurso “3”);
- [ ] Se, no campo “Observação” da GRU, foi informado o número do documento hábil, o nome favorecido (credor), número do contrato e informação das retenções;

</p>
</details> 

<details><summary>GUIA DA PREVIDÊNCIA SOCIAL – GPS</summary>
<p>

- [ ] Se o campo “RECOLHEDOR” foi preenchido com o CPF/CNPJ do recolhedor, no caso de PF o recolhedor é a própria UG emitente;
- [ ] Se o código de pagamento é 2631 – PJ e 2100 – PF;
- [ ] Se a competência é o mês de emissão da nota fiscal;
- [ ] Recurso “3”; 
- [ ] Verificar, levando-se em consideração o valor de “Base de Cálculo” e o percentual das alíquotas, se o valor recolhido está correto; e
- [ ] Se no campo “Observação” foram identificados os tributos, valores, a alíquota daretenção, e o número do documento hábil.e o campo “RECOLHEDOR” foi preenchido com o CPF/CNPJ do recolhedor, no caso PF o recolhedor é a própria UG emitente;
- [ ] Se o código de pagamento é 2631 – PJ e 2100 – PF;
- [ ] Se a competência é o mês de emissão da nota fiscal;
- [ ] Recurso “3”; 
- [ ] Verificar, levando-se em consideração o valor de “Base de Cálculo” e o percentual das alíquotas, se o valor recolhido está correto; e
- [ ] Se no campo “Observação” foram identificados os tributos, valores, a alíquota daretenção, e o número do documento hábil.

</p>
</details> 

<details><summary>NOTA DE DOTAÇÃO – ND</summary>
<p>

- [ ] Itens da classificação Orçamentária (Relatório Orçamento no Tesouro Gerencial):
- [ ] Esfera;
- [ ] PTRES;
- [ ] Fonte;
- [ ] Grupo de Despesa;
- [ ] Observação;
- [ ] Se o valor reduzido ( R ) é igual ao valor adicionado ( A );
- [ ] A alteração de QDD só pode ocorrer dentro do mesmo grupo de despesa.Itens da classificação Orçamentária (Relatório Orçamento no Tesouro Gerencial):
- [ ] Esfera;
- [ ] PTRES;
- [ ] Fonte;
- [ ] Grupo de Despesa;
- [ ] Observação;
- [ ] Se o valor reduzido ( R ) é igual ao valor adicionado ( A );
- [ ] A alteração de QDD só pode ocorrer dentro do mesmo grupo de despesa.

</p>
</details> 

<details><summary>NOTA DE CRÉDITO – NC</summary>
<p>

- [ ] Observação; e
- [ ] UG favorecida.

</p>
</details> 

<details><summary>PROGRAMAÇÃO FINANCEIRA – PF</summary>
<p>

- [ ] Observação; e
- [ ] UG favorecida.

</p>
</details> 

<details><summary>DOCUMENTO DE ARRECADAÇÃO MUNICIPAL – DAR</summary>
<p>

- [ ] Se o campo “RECOLHEDOR” foi preenchido com o CPF/CNPJ do recolhedor;
- [ ] Verificação do campo recurso;
- [ ] Verificação do campo referência; e
- [ ] Verificação do campo receita.

</p>
</details> 

<details><summary>PRÉ-EMPENHO</summary>
<p>

- [ ] Verificar data limite, se o tempo estimado está dentro da razoabilidade;
- [ ] Verificar se o campo observação está sucinto e objetivo;
- [ ] Verificar espécie: item evento;
- [ ] Itens da classificação orçamentária:
- [ ] Esfera
- [ ] PTRES
- [ ] Fonte
- [ ] ND
- [ ] UGR
- [ ] PI

</p>
</details> 

_Originally posted by @luanvsky in https://github.com/luanvsky/confreg-dw-v.0/issues/76#issuecomment-1822765822_
            </div>

**Comment by luanvsky** [comment]
[Manual Conformidade ifsuldeminas](https://portal.ifsuldeminas.edu.br/images/PROAD/Manuais/manual-conformidade-final.pdf
)
